# Generated by Django 5.1.3 on 2024-11-16 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('congress', models.IntegerField()),
                ('origin_chamber', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('update_date', models.DateTimeField()),
                ('introduced_date', models.DateField()),
                ('latest_action_date', models.DateField()),
                ('title', models.TextField()),
                ('policy_area', models.CharField(blank=True, max_length=255)),
                ('data', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('action_code', models.CharField(blank=True, max_length=255)),
                ('action_date', models.DateField()),
                ('action_time', models.TimeField(blank=True, null=True)),
                ('source_system', models.CharField(max_length=255)),
                ('source_system_code', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField()),
                ('type', models.CharField(max_length=255)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='congress_api.bill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillActionCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('system_code', models.CharField(max_length=255)),
                ('bill_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='congress_api.billaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('congress', models.IntegerField()),
                ('number', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('update_date', models.DateTimeField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='congress_api.bill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('system_code', models.CharField(max_length=255)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='congress_api.bill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillCosponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('bioguide_id', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('party', models.CharField(max_length=2)),
                ('state', models.CharField(max_length=2)),
                ('district', models.CharField(max_length=2)),
                ('is_original_cosponsor', models.BooleanField()),
                ('sponsorship_date', models.DateField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosponsors', to='congress_api.bill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillRelatedBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('congress', models.IntegerField()),
                ('number', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_bills', to='congress_api.bill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('name', models.TextField()),
                ('update_date', models.DateTimeField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='congress_api.bill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('action_date', models.DateField()),
                ('description', models.TextField()),
                ('text', models.TextField()),
                ('update_date', models.DateTimeField()),
                ('version_code', models.CharField(max_length=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='congress_api.bill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillTextVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('type', models.CharField(max_length=255)),
                ('version_datetime', models.DateTimeField()),
                ('text_url', models.URLField(blank=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('xml_url', models.URLField(blank=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_versions', to='congress_api.bill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('title', models.TextField()),
                ('text_version_code', models.CharField(max_length=255)),
                ('text_version_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('type_code', models.IntegerField()),
                ('update_date', models.DateTimeField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='congress_api.bill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
