# Generated by Django 5.1.3 on 2024-11-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress_api', '0002_rename_billtitles_billtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billtextversion',
            name='version_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
