# Generated by Django 5.1.3 on 2024-11-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress_api', '0003_alter_billtextversion_version_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseFloorAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('update_datetime', models.DateTimeField()),
                ('action_id', models.CharField(max_length=255)),
                ('unique_id', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('action_item', models.CharField(blank=True, max_length=255)),
                ('bill_ids', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
