# Generated by Django 5.1.3 on 2024-11-19 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress_api', '0004_houseflooraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bioguide_id', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('party', models.CharField(max_length=2)),
                ('state', models.CharField(max_length=2)),
                ('district', models.CharField(blank=True, max_length=2)),
                ('is_by_request', models.BooleanField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='congress_api.bill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
