# Generated by Django 5.1.3 on 2024-11-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress_api', '0005_billsponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='billcommittee',
            name='chamber',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billcommittee',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billcommittee',
            name='type',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
