# Generated by Django 5.1.3 on 2024-11-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress_api', '0006_billcommittee_chamber_billcommittee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billaction',
            name='committee',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='BillActionCommittee',
        ),
    ]
